### ISSUE TITLE
Error upon placing or removing part in VAB with both B9partswitch and tweakscale modules on vessel

### ISSUE THREAD

**Issue by 321nick** [net-lisias-ksp/TweakScale#159] opened 2021-01-25 13:59 UTC
details here: https://forum.kerbalspaceprogram.com/index.php?/topic/179030-ksp-144-tweakscale-under-lisias-management-2445-2021-0120/&do=findComment&comment=3914457

**Comment by Lisias** [comment] 2021-02-07 03:30
Yes, it's a bug. But until the moment, it was not determined to be related to TweakScale - TweakScale appears to be the screaming victim on this mess.

It's the same thing as these [two](https://forum.kerbalspaceprogram.com/index.php?/topic/179030-ksp-144-tweakscale-under-lisias-management-2445-2021-0120/&do=findComment&comment=3910170) other [problems](https://forum.kerbalspaceprogram.com/index.php?/topic/179030-ksp-144-tweakscale-under-lisias-management-2445-2021-0120/&do=findComment&comment=3906220) reported earlier - that I didn't reproduced on my rig, by the way, besides installing B9PS with some other combinations of add'ons (that used to cause problems in the past, but not nowadays).

So, until someone manage to build a very straight forward way of forcing this problem (install KSP, TweakScale, B9PW and this add'on), I`m afraid I can`t be of too much help - I just can't fix what I can see (and it`s on TweakScale), and until the moment, I could not reproduce this on TweakScale (and I tried).

I will check your KSP.log by night, but I have little to no hope to find something I can fix.

In a way or another, TweakScale is deprecating all patches non Stock and non DLC, with third party support being implemented on the [TweakScale Companion Program](https://forum.kerbalspaceprogram.com/index.php?/topic/192216-tweakscale-companion-program-2020-1228/). Assuming this is not a bug on some third party patch or part config and TweakScale needs to support something new, this something new will be implemented on a Companion.

**Comment by Lisias** [comment] 2021-02-07 03:31
Marking it as support and unrelated as until this moment it was not possible to determine it's a problem on TweakScale.

I will keep this open, however, to give it further attention as time allows.

**Comment by Lisias** [comment] 2021-10-17 20:09
I wonder if this was not related to #168 , fixed by the pull request https://github.com/blowfishpro/B9PartSwitch/pull/207 ?

In a way or another, I think it's time to close this.

**Closed by Lisias** 2021-10-17 20:09 UTC
Labels: unrelated, support
