### ISSUE TITLE
Same as #227, in addition of can’t save, launch, load stock crafts or even leaving the vab/sph

### ISSUE THREAD

**Issue by harrytherocketeer** [net-lisias-ksp/TweakScale#231] opened 2022-01-15 09:52 UTC
Will send log to you later since I’m on mobile @lisias

**Comment by harrytherocketeer** [comment] 2022-01-15 09:55
Also I’m using 1.12.2, and no, the 999 redist file didn’t duplicate.

**Comment by Lisias** [comment] 2022-01-16 07:19
I'm waiting for the KSP.log - whatever is borking on you, it's logged there.

**Comment by harrytherocketeer** [comment] 2022-01-16 08:22
In exam week rn so please have patience.

**Comment by harrytherocketeer** [comment] 2022-01-16 08:49
[KSP.log](https://github.com/net-lisias-ksp/TweakScale/files/7876618/KSP.log)
@Lisias here you go

**Comment by harrytherocketeer** [comment] 2022-01-16 08:50
huh
It doesnt record the warning

**Comment by harrytherocketeer** [comment] 2022-01-16 08:54
![image](https://user-images.githubusercontent.com/96720348/149653527-e0aec13f-4710-4d56-b5cf-fb2cde0feaa4.png)

**Comment by harrytherocketeer** [comment] 2022-01-16 09:04
the log doesnt even update anymore

**Comment by Lisias** [comment] 2022-01-16 20:29
@harrytherocketeer ,

> the log doesnt even update anymore

This is something pretty weird - and unfortunate, because without the KSP.log I have my hands tied. It can be anything, absolutely anything being badly loaded before it's TweakScale's time.

Do you know hot to get the Player.log? It is not as convenient as KSP.log, but the information is almost the time logged there too!

Read the Spoiler under the tiitle *Support* on the [TweakScale's OP](https://forum.kerbalspaceprogram.com/index.php?/topic/179030-130/&do=findComment&comment=3469313) for further instructions!

**Comment by harrytherocketeer** [comment] 2022-01-17 11:33
@lisias
Seems like the problem has been solved, the solution is as simple as NOT installing from Ckan.
Also I reinstalled the game and the log seems to be finally working again :)

**Comment by harrytherocketeer** [comment] 2022-01-17 12:24
This does not mean the issue is completely solved however, as new players will continue downloading Tweakscale from CKAN, and most likely, will found the same issue.

**Comment by harrytherocketeer** [comment] 2022-01-17 12:28
Also can I scale command modules (Drone core, guidance units, command pods and cockpits - probably passenger modules too)?

**Comment by Lisias** [comment] 2022-01-17 22:16
> Also can I scale command modules (Drone core, guidance units, command pods and cockpits - probably passenger modules too)?

Yes. But the crew capacity **will not** scale up because Squad [shut that door on my face](https://forum.kerbalspaceprogram.com/index.php?/topic/179030-130/page/48/#comment-3702846) recently.

I can't workaround this one, I will need to write a new module to overcome this heavy handed move from the Developers - what means this is going to take a while.

On the not so bad news, the crew capacity will scale down normally,

**Comment by Lisias** [comment] 2022-01-17 22:29
Interesting…. 

I just checked the download from SpaceDock, then I checked the github's packages, then I checked the TweakScale's netkan file on the CKAN's NetKan repository.

Everything is all right.

It worths to mention that recently I had an unfortunate incident with one of the Forum's moderator that had a problem with the `999_Scale_Redist.dll` file being wrongly copied into his sacred KSP copy.

Boy, he was pissed off…

It ended up that CKAN, without him being aware, had included his sacred KSP into the the updating pool and when he installed TweakScale on a testbed of him, CKAN also copied the file into his sacred KSP installment, screwing his main gaming. Deleting the file was enough.

You know what? This is sounding like a bug on CKAN itself! He's copying the `999_Scale_Redist.dll` file into the wrong place!!!!!!

**Comment by Lisias** [comment] 2022-01-17 22:36
@harrytherocketeer In time, remember to remove `FerramAerospaceResearch/Plugins/Scale_Redist` when installing TweakScale.

There can be only **ONE** copy of Scale_Redist, and it must be at `GamaData\999_Scale_Redist.dll` .

**Comment by harrytherocketeer** [comment] 2022-01-18 00:05
Huh. I’ll check it later.

**Comment by harrytherocketeer** [comment] 2022-01-18 00:09
> > Also can I scale command modules (Drone core, guidance units, command pods and cockpits - probably passenger modules too)?
> 
> Yes. But the crew capacity **will not** scale up because Squad [shut that door on my face](https://forum.kerbalspaceprogram.com/index.php?/topic/179030-130/page/48/#comment-3702846) recently.
> 
> I can't workaround this one, I will need to write a new module to overcome this heavy handed move from the Developers - what means this is going to take a while.
> 
> On the not so bad news, the crew capacity will scale down normally,

Also there’s other things like monopropellant and inventory capacity and other things (I do install Kerbalism and looks like Realfuel changes monopropellant into hydrazine) does that also scales with the size?

**Comment by harrytherocketeer** [comment] 2022-01-18 09:36
> @harrytherocketeer In time, remember to remove `FerramAerospaceResearch/Plugins/Scale_Redist.dll` when installing TweakScale.
> 
> There can be only **ONE** copy of Scale_Redist, and it must be at `GamaData\999_Scale_Redist.dll` .

Seems like you're right. Not removing it makes the houston warning reappear.

**Comment by harrytherocketeer** [comment] 2022-01-18 13:12
@Lisias Seems like the problem is not the ferram scale_redist, CKAN, or any other sources. Looks like you have to run the game directly in it's folder location instead of the Windows search bar (Bottom left, right next to the Windows symbol).

**Comment by harrytherocketeer** [comment] 2022-01-18 13:13
Each time I run KSP by searching the windows bar the problem reappears

**Comment by Lisias** [comment] 2022-01-19 04:47
> Each time I run KSP by searching the windows bar the problem reappears

AHHH!!! Now I understand!!! :D

If you create a icon on the Desktop, our launch it using Steam or GOG (if you use them), I suppose the problem doesn't happens, right?

**Comment by harrytherocketeer** [comment] 2022-01-19 07:14
Possibly so.

**Comment by Lisias** [comment] 2022-01-20 02:15
@harrytherocketeer , this is what's happening!

There's a thingy called "default" or "current" directory. It's the directory that will be used by the program if it tries to access a file by a partial pathname.

KSP Add'Ons assume that the current directory **is the same directory** where the main executable is, and this is usually the case.

BUT….

Usually is not the same as always. On UNIX, when you launch a program using a graphic shell, the current directory is not automatically changed to the path where the executable is - there's a long discussion about this here: https://github.com/net-lisias-ksp/KSPAPIExtensions/issues/12

What you can do to check this is to install KSPe - https://github.com/net-lisias-ksp/KSPAPIExtensions/releases . It's a library that some forks of mine use, so it will not be useful to you, except by the sanity checks it does on the runtime environment. It will yells if I'm right about the problem.

Since it must be used by some add'on, it's safe to install - and you can remove it later after the diagnosing is done.

Let me know what you want to do.

**Comment by harrytherocketeer** [comment] 2022-01-20 04:02
Ok, I’ll try that.
Also Tweakscale states 13 parts failed sanity checks. Although I’ll assume that’s just normal, since I installed a lot of mods, and I don’t really think you would have Tweakscale configs for Near Future Exporation, Launch Vehicles and Kerbal Atomics.

**Comment by Lisias** [comment] 2022-01-23 10:53
@harrytherocketeer 

> Ok, I’ll try that.
> Also Tweakscale states 13 parts failed sanity checks. Although I’ll assume that’s just normal, since I installed a lot of mods, and I don’t really think you would have Tweakscale configs for Near Future Exporation, Launch Vehicles and Kerbal Atomics.

Take a look on https://github.com/net-lisias-ksp/TweakScaleCompanion_PKMC/releases - there *some** support available, all work in progress.

Failed sanity checks are usually only relevant when something goes wrong - most of the time, it means TS could not check these parts by some reason. It's not a good sign, but I could not determine it's always signs of trouble.

**Comment by harrytherocketeer** [comment] 2022-01-23 11:04
> 

Thanks!
Can I download it on CKAN, or use the manual way of modding?

**Comment by harrytherocketeer** [comment] 2022-01-23 11:06
> @harrytherocketeer
> 
> > Ok, I’ll try that.
> > Also Tweakscale states 13 parts failed sanity checks. Although I’ll assume that’s just normal, since I installed a lot of mods, and I don’t really think you would have Tweakscale configs for Near Future Exporation, Launch Vehicles and Kerbal Atomics.
> 
> Take a look on https://github.com/net-lisias-ksp/TweakScaleCompanion_PKMC/releases - there _some_* support available, all work in progress.
> 
> Failed sanity checks are usually only relevant when something goes wrong - most of the time, it means TS could not check these parts by some reason. It's not a good sign, but I could not determine it's always signs of trouble.

Thanks! Can I download using CKAN or use the traditional way of adding mods?

**Comment by Lisias** [comment] 2022-01-23 15:03
> Thanks! Can I download using CKAN or use the traditional way of adding mods?

They are not available on CKAN for while - I need to work out some details first. I had some weird reports from CKAN users that, if confirmed, may hinder packaging the Companions the way it was intended to be.

Problem: time. I need to time to check CKAN on this, but I already have my hands full due KSP itself.

**Comment by harrytherocketeer** [comment] 2022-01-23 15:21
> > Thanks! Can I download using CKAN or use the traditional way of adding mods?
> 
> They are not available on CKAN for while - I need to work out some details first. I had some weird reports from CKAN users that, if confirmed, may hinder packaging the Companions the way it was intended to be.
> 
> Problem: time. I need to time to check CKAN on this, but I already have my hands full due KSP itself.

I’m already having a plan of trying to make mods work together (mostly creating configs for Realfuel), but the problem is…I don’t know how to program anything except a little ping pong game from Scratch. lol

**Comment by Lisias** [comment] 2022-01-25 21:43
@harrytherocketeer ,

> I’m already having a plan of trying to make mods work together (mostly creating configs for Realfuel), but the problem is…I don’t know how to program anything except a little ping pong game from Scratch. lol

Most integrations are done on Config Files nowadays - i.e., Module Manager. :)

I think you should start with it - you will need it anyway even by coding on C#, because it's the best (if not the only safe) way to inject your features on existing parts.

Can I close this? Or do you need some more assistance on something? (no worries, the issue is already here, let's make good use of it!!)

**Comment by harrytherocketeer** [comment] 2022-01-28 13:35
I think I'm fine for now.

**Comment by harrytherocketeer** [comment] 2022-01-28 13:35
> @harrytherocketeer ,
> 
> > I’m already having a plan of trying to make mods work together (mostly creating configs for Realfuel), but the problem is…I don’t know how to program anything except a little ping pong game from Scratch. lol
> 
> Most integrations are done on Config Files nowadays - i.e., Module Manager. :)
> 
> I think you should start with it - you will need it anyway even by coding on C#, because it's the best (if not the only safe) way to inject your features on existing parts.
> 
> Can I close this? Or do you need some more assistance on something? (no worries, the issue is already here, let's make good use of it!!)

I think I'm fine now.

**Comment by Lisias** [comment] 2022-01-28 23:00
Cheers!

**Closed by Lisias** 2022-01-28 23:00 UTC
Labels: unrelated, support
