### ISSUE TITLE
Just a thought ...

### ISSUE THREAD

**Issue by 7ranceaddic7** [net-lisias-ksp/TweakScale#130] opened 2020-07-28 12:52 UTC
Do you know about MM's handling of Dynamic Modules?  Could this be in any way related to any of the issues TS encounters during prefab?

https://github.com/sarbian/ModuleManager/wiki/Managing-Dynamic-Modules

**Comment by Lisias** [comment] 2020-07-28 21:08
Great Scott!!! #docEmmetFeelings -- couldn't resist! :)

Yes, this came to my mind once. On last Friday, if memory serves me right, when I was researching about MM Extensions that once existed but apparently, doesn't anymore (so I ended up shoving yet a new feature on KSPe.)

I had searched MM's source code for MM_DYNAMIC and even [MM_REINITIALIZE](https://github.com/sarbian/ModuleManager/issues/73), and didn't found anything.

So I gone for the git log:

```
macmini62:ModuleManager lisias$ git log -S MM_DYNAMIC --source --all

commit a94ffcb8db5c865a0e4e47a13214d2c245d96037	refs/tags/v2.2.3
Author: Sarbian <Sarbian@sarbian.com>
Date:   Mon Aug 18 23:04:35 2014 +0200

    Remove the SaveGameFixer class to avoid an error message since it's not used ATM.

commit 3bdb26e9a19e994f8c2ae6219acc337aa9d40d60	refs/remotes/wiki/master
Author: Swamp-Ig <Swamp-Ig@users.noreply.github.com>
Date:   Wed May 21 00:19:43 2014 -0700

    Updated Managing Dynamic Modules (markdown)

commit 137ef60e22be302d766dfe7b262cbd28fbb6c47b	refs/remotes/wiki/master
Author: Swamp-Ig <Swamp-Ig@users.noreply.github.com>
Date:   Sun May 18 15:21:05 2014 -0700

    Updated Managing dynamic modules (markdown)

commit 1eccc91168789713c03b867f678fb1cfcc05e3e7	refs/remotes/origin/upstream/2.0.7_SaveFixer
Author: Sarbian <Sarbian@sarbian.com>
Date:   Thu May 8 17:04:37 2014 +0200

    add savefixer

commit d865c4a6be05d76bfb7e3d1166a683e11628050c	refs/tags/2.1.1
Author: Swamp Ig <kerbal@ninjateaparty.com>
Date:   Thu May 8 15:01:18 2014 +0800

    Better logging and backups

commit eeb9fe51f34c2fe06afa6da93f12df02b32a4930	refs/tags/2.1.1
Author: Swamp Ig <kerbal@ninjateaparty.com>
Date:   Wed May 7 22:20:40 2014 +0800

    Added SaveGameFixer
```

And examined every single one of that commits, and came to this:

The file that implemented it was deleted here https://github.com/net-lisias-ksp/ModuleManager/commit/a94ffcb8db5c865a0e4e47a13214d2c245d96037#diff-72772e71ce23465fc025958f04eda35a

Then it came back here: https://github.com/net-lisias-ksp/ModuleManager/commit/1eccc91168789713c03b867f678fb1cfcc05e3e7#diff-72772e71ce23465fc025958f04eda35a

And then finally removed again here: https://github.com/net-lisias-ksp/ModuleManager/commit/a94ffcb8db5c865a0e4e47a13214d2c245d96037

So this thing doesn't exists anymore on MM since MM 2.4.2. So this cannot be a fix for this problem, and Allista's issue I linked hinted someone else had looked on the matter in the past too.

However... I doubt this would be of any help, because I think something else is shoving data from the prefab into living savegames (and I'm pretty sure I found, but need more testings to be sure) and this started to happen on somewhere from 1.5.1 to 1.6.1 (I skipped a lot of KSP versions, gone from 1.4.5 to 1.7.1). On 1.4.x I was used to edit craft files to brute force my way on changing parts as a fast prototyping mechanism. On KSP 1.7 (and I confirmed it on 1.6.1 IRRC) I noticed that my editions was being tampered when I loaded the craft on the editor (and later I confirmed the behaviour on savegames too). And the recent blunt resource overwrite we had on KSP 1.9 also hints me that this is not something on MM anymore.

**Comment by 7ranceaddic7** [comment] 2020-07-28 22:04
LoL  Go figure.  I'm a few days late.

Ah, well, that KSP_VERSION check looks interesting.

**Comment by Lisias** [comment] 2020-07-29 06:29
Yep. But not the only solution, I came to an alternative solution on Impossible Innovations:

https://github.com/net-lisias-ksp/ImpossibleInnovations/blob/master/GameData/ImpossibleInnovations/Parts/Engines/II-CL-20Flea/CL20Flea.cfg

It's not so versatile as the KSP_VERSION , but it's good enough to me. I just added a handler to ModuleManagerAddToModList and shoved TAGs for KSP versions from 1.1. to the current one (so I can do conditionals with ranges).

**Comment by 7ranceaddic7** [comment] 2020-07-29 21:11
Is that wise - adding a handler to ModuleManagerAddToModList?  Isn't this diverging your fork of ModuleManager further away from canon?

Also, I'm not understanding how the :NEEDS[KSP-1.2, !KSP-1.5] works. I see a few problems with it according to known syntax:

(1) that usage says: use this in KSP-1.2 and not KSP-1.5 making
(2) the !KSP-1.5 unnecessary, and
(3) it is likely to throw an error.

**Comment by Lisias** [comment] 2020-07-29 21:27
> Is that wise - adding a handler to ModuleManagerAddToModList? Isn't this diverging your fork of ModuleManager further away from canon?

My fork, frankly, is a test bed for new ideas. I can consider adding something to test and to be used **only** by the KSPU add'ons (that are by themselves stunts to test new ideas too). But anything published on the KSP hierarchy **will** work with canon, point. Since II is published on my net-lisias-ksp hierarchy, what I coded there works with stock MM.

The `ModuleManagerAddToModList` is canon, it's on "stock" MM for some time and it's used by Kerbalism.  ;) 


> Also, I'm not understanding how the :NEEDS[KSP-1.2, !KSP-1.5] works.

It's the way I found to implement ranges. KSPe adds to MM tags from KSP 1.1 to the currently used one in minor versions increments. So, KSP 1.4.3 will have the tags KSP-11, KSP-12, KSP-13 and KSP-14 available.

KSP 1.5.0 and 1.5.1 will have them, plus KSP 1.5.

So if you to define something to be used from KSP KSP 1.3.0 to KSP 1.4.5, you state `:NEEDS[KSP-13,!KSP-15]`. This will demand that KSP-13 tag be defined (what just happens on 1.3.0 and forward), but if KSP-15 is defined (what happens from KSP 1.5.0 until KSP 1.10.1 by now), it will be ruled out. The aftermath is that now we have a range defined.


> (1) that usage says: use this in KSP-1.2 and not KSP-1.5 making

Nope. It says "use this when the tag KSP-12 is present, but do not use this if KSP-15 is present". :NEEDS only recognizes the presence of a tag, we can create tags to simulate some semantics, but in the end, it only detects the present or the absence (by using `!`) of a tag.


> (2) the !KSP-1.5 unnecessary, and

On that case, it's necessacy because that model is only present from KSP 1.2 to KSP 1.4.5 . So , if the user is using KSP 1.5, that model is not present and the patch must use something else.


> (3) it is likely to throw an error.

Nope. it works. I test things before publishing it. Most of the time, at least. :)

(I have test beds from KSP 1.1 to KSP 1.10.1 - and I make use of them, most of the time for pure curiosity)

**Comment by Lisias** [comment] 2020-07-29 21:44
Oh, yes... O forgot to mention. II needs KSPe, a subcomponent from [KSPApiExtentions/L](https://github.com/net-lisias-ksp/KSPAPIExtensions/releases)

You need to have it installed. (and ClickThroughBlock too, as it's a dependency of KSPe.UI)

**Comment by Lisias** [comment] 2020-07-29 21:46
About `ModuleManagerAddToModList`, I just realised that it's used by Kopernicus too! :)

https://github.com/search?q=ModuleManagerAddToModList&type=Code

**Comment by Lisias** [comment] 2020-07-29 22:16
And here is the code where `ModuleManagerAddToModList` is implemented on Stock MM:

https://github.com/sarbian/ModuleManager/blob/e0da6ba13bca4dea7181cd009b49691d9fd47df0/ModuleManager/ModListGenerator.cs#L176 (for static methods)

https://github.com/sarbian/ModuleManager/blob/e0da6ba13bca4dea7181cd009b49691d9fd47df0/ModuleManager/ModListGenerator.cs#L210 (for methods on loaded instances of MonoBehaviour).

**Comment by Lisias** [comment] 2020-07-29 22:47
And to avoid the slightest chance of doubt, KSP.log and Stock MM logs from a test run using KSPe 2.2.0.2, TS 2.4.3.20 and II 0.8.9.0 on KSP 1.10.1 :)

* [KSP.log](https://github.com/net-lisias-ksp/TweakScale/files/4997867/KSP.log)
* [MMPatch.log](https://github.com/net-lisias-ksp/TweakScale/files/4997868/MMPatch.log)
* [ModuleManager.log](https://github.com/net-lisias-ksp/TweakScale/files/4997869/ModuleManager.log)

**Comment by 7ranceaddic7** [comment] 2020-07-30 02:57
Oh, I don't doubt you, I understand how much the end-user experience means to you. I apologize if you felt I implied you were not working within the MM framework. I didn't realize the ModuleManagerAddToModList was MM canon. That's my bad, I apologize.

RE: `:NEEDS`

The sequential tagging was what I was missing. That makes more sense now. Thank you.

**Comment by 7ranceaddic7** [comment] 2020-07-30 02:59
And, TBC, I really appreciate your explaining things to me. You make things clear for an old fart like me to understand.

**Comment by Lisias** [comment] 2020-07-30 08:07
> Oh, I don't doubt you, I understand how much the end-user experience means to you. I apologize if you felt I implied you were not working within the MM framework. I didn't realize the ModuleManagerAddToModList was MM canon. That's my bad, I apologize.

Not a problem by itself. I'm somewhat picky on the subject because in the past such statements were made in not exactly the best of faiths (obviously, by different people and with different intents), and at that time this caused some bad reputation to TweakScale (and me). And since I was also targeted on some trolling on my personal digital accounts, I also became a bit jumpy on the subject. :P 

So I'm kinda wired to be absolutely clear and detailed while explaining why such statements is wrong. God knows when someone else will drop here and see the statement and start to repeat it on the wild, and I will have to fight the same fire again.

(not your fault, it just happened you had stepped on a small amount of dirty that revealed itself soft and smelly...)


> RE: `:NEEDS`
> 
> The sequential tagging was what I was missing. That makes more sense now. Thank you.

On your defense, I mentioned ranges but didn't exactly explained how it works until late on the conversation. People usually skip obvious details, and since I was the one the coded the stunt, it's pretty obvious to me and I usually forget it's obvious only to me!

**Closed** 2020-07-30 14:29 UTC
