### ISSUE TITLE
After Updating to KSP 1.10 and TweakScale 2.4.3.19 my older crafts got re sized to default size

### ISSUE THREAD

**Issue by divjot1** [net-lisias-ksp/TweakScale#129] opened 2020-07-26 10:13 UTC
![Kerbal Space Program 26-07-2020 15_17_21](https://user-images.githubusercontent.com/68808848/88476536-b6d87e80-cf56-11ea-8ef8-2f995ae82937.png)

**Comment by 7ranceaddic7** [comment] 2020-07-26 10:54
Upload logs (KSP.log & Player.log) to a file server for review.

**Comment by Lisias** [comment] 2020-07-26 12:15
There's something wrong on your instalment - something is missing, or installed wrongly. The KSP.log and the Player.log (as asked by @7ranceaddic7 ) will tell me what's going wrong.

BUT... The most usual mistake is failing to install `999_Scale_Redist.dll` on the GameData Folder (on the same place ModuleManager is).

On the old days of KSP 1.7.3 and previous ones, the `Scale_Redist.dll` could be distributed by anyone wanting to use it, but something changed on KSP 1.8 and from there, you **MUST** install `999_Scale_Redist.dll` on the GameData in order to have things working.

It worth to mention that this is explained on the [INSTALL.md](https://github.com/net-lisias-ksp/TweakScale/blob/master/INSTALL.md) file.:

```
* Extract the package's GameData/ folder into your KSP's as follows:
     * <PACKAGE>/GameData/TweakScale --> <KSP_ROOT>/GameData
     * <PACKAGE>/GameData/999_Scale_Redist.dll --> <KSP_ROOT>/GameData
          * Overwrite any preexisting file.
```

Please advise if this is your case, @divjot1 , so I can close this issue.

Cheers!

**Comment by divjot1** [comment] 2020-07-26 14:31
Yes, it seems as if I have not Installed 999_Scale_Redist.dll, but I am not able to find that file in any of the files I have downloaded, could you send a link to it.
Thank you!

**Comment by divjot1** [comment] 2020-07-26 14:36
[KSP.log](https://github.com/net-lisias-ksp/TweakScale/files/4977781/KSP.log)
Here is my KSP.log

**Comment by Lisias** [comment] 2020-07-26 19:27
Yep, you don't have it there!

```
Environment Info
Win32NT 7FFFFFFFFFFFFFFF  Args: KSP_x64.exe

Mod DLLs found:
Stock assembly: Assembly-CSharp v0.0.0.0
ModuleManagerWatchDog v0.0.1.0
ModuleManager v4.1.4.0
KSP-Recall v0.0.3.2
KSPe.Light.Recall v2.1.1.6
Resourceful v0.0.3.2
Stock assembly: KSPSteamCtrlr v0.0.1.35

Folders and files in GameData:
999_KSP-Recall
ModuleManagerWatchDog
Stock folder: Squad

Stock folder: SquadExpansion

TweakScale
__LOCAL
666_ModuleManagerWatchDog.dll
ModuleManager.4.1.4.dll
ModuleManager.ConfigCache
ModuleManager.ConfigSHA
ModuleManager.Physics
ModuleManager.TechTree
```
The `999_Scale_Redist.dll` should be there, after the `666_ModuleManagerWatchDog.dll` - that, surprisingly, it's there! :)

Github had changed the U.I. Some things are harder to find now - at least, until we discover where they are now. The Releases link was moved to the right lateral bar on the main page:

![Screen Shot 2020-07-26 at 16 21 11](https://user-images.githubusercontent.com/64334/88487546-6e23c400-cf5c-11ea-9cf5-86770f51e555.png)

At least the links didn't changed. :)

The latest release can be fount here: https://github.com/net-lisias-ksp/TweakScale/releases

**Comment by Lisias** [comment] 2020-07-26 19:30
Just to be extra sure (I need more sleeptime - or stronger coffee!), I just confirmed that the DLL is indeed on the distribution file (better safe than sorry)

![Screen Shot 2020-07-26 at 16 28 29](https://user-images.githubusercontent.com/64334/88487621-42eda480-cf5d-11ea-984c-7d90ed692e21.png)

**Comment by Lisias** [comment] 2020-07-26 19:31
Just to be extra sure (I need more sleeptime - or stronger coffee!), I just confirmed that the DLL is indeed on the distribution file (better safe than sorry)

![Screen Shot 2020-07-26 at 16 30 33](https://user-images.githubusercontent.com/64334/88487641-64e72700-cf5d-11ea-963f-47cb446edc26.png)

**Comment by 7ranceaddic7** [comment] 2020-07-26 21:33
@divjot1 

When updating a mod manually I:
- 1) open two windows sxs, 
- 2) drill down to inside the GameData,
- 3) delete everything in my game that is present in the mod,
- 4) drag/drop the update to install.

I've also adopted a hierarchy technique similar to TS. @Lisias uses `GameData/__Local/` for temporary files not intended to be permanent. I use `GameData/__myLocal/` for my personal MMConfigs with a internal hierarchy like `GameData/`, so I know what mod I'm altering.

With this setup, I don't have to know what TS modifies in `__Local` and I can follow the above mindlessly. The `__` forces the folder to the top of the directory.

**Comment by Lisias** [comment] 2020-07-27 15:40
> I've also adopted a hierarchy technique similar to TS. @Lisias uses `GameData/__Local/` for temporary files not intended to be permanent. I use `GameData/__myLocal/` for my personal MMConfigs with a internal hierarchy like `GameData/`, so I know what mod I'm altering.

humm... I hadn't thought of that... 

I discovered a new trick on KSP, I'm testing it on every older KSP I have access (anything older than 1.0.5 is not available on Steam anymore. damn it) to double check the stunt.

If I'm right, there's a yet **better** place for your own customisations. :) Stay tuned!

**Comment by divjot1** [comment] 2020-07-31 17:42
no matter what I tried it didn't let me resize any parts, so I've just gone back to the last update

**Comment by Lisias** [comment] 2020-07-31 21:35
> no matter what I tried it didn't let me resize any parts, so I've just gone back to the last update. At least I'm able to use all my mods now, I'll update after a month or so, If there are any more updates or bug fixes

But it was what I said. From your last log, I detected that you forgot to install 999_Scale_Redist.dll :

```
************************************************************************

Environment Info
Win32NT 7FFFFFFFFFFFFFFF  Args: KSP_x64.exe

Mod DLLs found:
Stock assembly: Assembly-CSharp v0.0.0.0
ModuleManagerWatchDog v0.0.1.0
ModuleManager v4.1.4.0
KSP-Recall v0.0.3.2
KSPe.Light.Recall v2.1.1.6
Resourceful v0.0.3.2
Stock assembly: KSPSteamCtrlr v0.0.1.35

Folders and files in GameData:
999_KSP-Recall
ModuleManagerWatchDog
Stock folder: Squad

Stock folder: SquadExpansion

TweakScale
__LOCAL
666_ModuleManagerWatchDog.dll
ModuleManager.4.1.4.dll
ModuleManager.ConfigCache
ModuleManager.ConfigSHA
ModuleManager.Physics
ModuleManager.TechTree
```

This is how MM reports my test rig:

```
************************************************************************

Environment Info
Unix 7FFFFFFFFFFFFFFF  Args: KSP

Mod DLLs found:
Stock assembly: Assembly-CSharp v0.0.0.0
ModuleManagerWatchDog v0.0.1.0
Scale_Redist v1.0.0.0 / v2.5.0.16
ModuleManager v4.1.3.2
KSP-Recall v0.0.3.2
KSPe.Light.Recall v2.1.1.6
Resourceful v0.0.3.2
KSPe.Light.TweakScale v2.1.1.6
Scale v2.5.0.16

Folders and files in GameData:
999_KSP-Recall
ModuleManagerWatchDog
Stock folder: Squad

Stock folder: SquadExpansion

TweakScale
__LOCAL
Stock file: .DS_Store

000_KSPe.dll
666_ModuleManagerWatchDog.dll
999_Scale_Redist.dll
```

See the difference? Perhaps you you installed TweakScale on the wrong place? Had you unzipped the files into KSP folder itself instead of the GameData?

**Comment by divjot1** [comment] 2020-08-06 17:07
I unzip it in a different folder then cut and paste the files inside the game data into the game data in the ksp folder

**Comment by Lisias** [comment] 2020-08-06 17:14
> I unzip it in a different folder then cut and paste the files inside the game data into the game data in the ksp folder

And how is the KSP.log you run KSP? post the KSP.log with the problem here (drag and drop it on the comment box, github does the rest) so I can inspect it.

**Comment by divjot1** [comment] 2020-08-06 17:27
Okay it seems to be working well now! I'll install all my other mods and let you know if there's any problem. Thanks!

**Closed** 2020-08-06 17:27 UTC
Labels: support
