### ISSUE TITLE
Exceptions thrown endlessly after picking up and releasing craft in editor, making it disappear

### ISSUE THREAD

**Issue by Alexsys** [net-lisias-ksp/TweakScale#221] opened 2021-11-26 07:08 UTC
Simply shift+clicking on a saved craft I have to reposition it, as soon as I click again to leave it in desired position it disappears aka goes invisible, and many excepetions being repeated endlessly (over 245 times as i write this) post this action as long as its invisible and you dont select to load a different craft, or the same one and just dont move it.

https://i.imgur.com/aoHMVNT.png

https://www.dropbox.com/s/0whexowvqv4816i/ModuleManager.log?dl=0 
https://www.dropbox.com/s/a83oo341kjt6pvo/KSP.log?dl=0

maybe these will be useful too
https://www.dropbox.com/s/3kyyi8jdxnyxga2/KSPDev-LOG.211126T073418.ERROR.txt?dl=0
https://www.dropbox.com/s/my61e3juepl3d8p/KSPDev-LOG.211126T073418.WARNING.txt?dl=0
https://www.dropbox.com/s/ftaq2jnulwehk9j/KSPDev-LOG.211126T073418.INFO.txt?dl=0

**Comment by Lisias** [comment] 2021-11-27 06:19
Ah, yes. The same case on KIS : https://github.com/ihsoft/KIS/issues/399

As far as I understood, TweakScale is not involved on this one. It's something related to Contract Configurator.

So, I'm closing this one.

**Comment by Lisias** [comment] 2021-11-27 18:49
Just to keep things update, CC apparently was not the culprit, as by removing it the problems start to blow up with someone else.

**Comment by Alexsys** [comment] 2021-11-28 02:29
> Just to keep things update, CC apparently was not the culprit, as by removing it the problems start to blow up with someone else.

Actually, I removed CC, so I shall retry with this same exact craft that was disappearing, i'll update once its done

cc is a tiny tumor

**Comment by Lisias** [comment] 2021-11-28 02:50
Ow, okey. let's handle this here too. I have no problem on it, so I reopened this. :)

**Comment by Alexsys** [comment] 2021-11-28 03:01
> Ow, okey. let's handle this here too. I have no problem on it, so I reopened this. :)

Honestly man, I dont want to waste your weekend with this shitfest bug my game does (which apparently is common in the game's approach to a mod festival),
but here's my finding.

It still continues, same exact behavior, with these logs
https://i.imgur.com/j9fna1p.jpeg
(as seen in the screenshot, craft is invisible after movement and this first exception keeps climbing in repeats number till I switch and load to some other craft)

The craft disappears after you move it in the editor still, no CC tumor installed.

**Comment by Lisias** [comment] 2021-11-29 16:41
I run out of time on the weekend, but I will look on this today by night.

**Comment by Lisias** [comment] 2021-12-01 19:47
(hell broke look on RL, sorry!)

**Comment by Lisias** [comment] 2021-12-02 14:39
@Alexsys,

Well, now hell broke loose on a coworker and, since this blocked me, I ended up with some time to burn.

From your log, the first exception I got was:

```
[LOG 11:17:02.198] [HighLogic]: =========================== Scene Change : From EDITOR to FLIGHT (Async) =====================
[EXC 11:17:03.166] NullReferenceException: Object reference not set to an instance of an object
        KIS.KISAddonPickup.Update () (at <717f3fbf4619476fb8c8266ee8d73162>:0)
        UnityEngine.DebugLogHandler:LogException(Exception, Object)
        ModuleManager.UnityLogHandle.InterceptLogHandler:LogException(Exception, Object)
        UnityEngine.Debug:CallOverridenDebugHandler(Exception, Object)
```

Other than that annoying Exception from Scatterer, I found nothing else that can be obviously linked to this problem.

Your options now are:

1. REMEMBER TO KEEP BACKUPS
2. Gradually remove unused Add'Ons (taking core to avoid removing dependencies), a small ammount each time, and rebooting KSP to see if the problems goes away. Remember to annotate the add'ons being removed on each round
3. On the exact round the problem vanishes, install back everything else but the ones from the last round.
4. This will help to rule out environment causes (memory, VRAM usage, etc).
5. **IF** the problem comes back, you have an environmental problem. **THIS IS A PAIN IN THE ASS** to diagnose, but at least we will know that it's not a bug on some add'on!
6. If the problem **DOES NOT** comes back, install that add'ons from the last round **one by one** until the problem happens again.
7. The last add'on installed will be culprit.
8. If the problem does not comes back, see item 6 above.

Right now, it's the best I can do for you. Let me know if you need further assistance.

**Comment by Alexsys** [comment] 2021-12-11 03:16
Aight

Been pc-less and just got it fresh, it'll take a bit to further test as of now

**Comment by Lisias** [comment] 2022-01-07 16:21
A silent customer is usually a happy one (or gone…). In the hopes of being the former, I'm closing this. Feel free to reopen it, @Alexsys , if needed. Also don't forget to mention me using "@" so I can respond faster!

Cheers!

**Closed by Lisias** 2022-01-07 16:21 UTC
Labels: unrelated, support

**Comment by Alexsys** [comment] 2022-01-07 17:21
PC got me off game, alas I'm out of KSP for the time being / having the ability to assist in up to date manner.
