### ISSUE TITLE
About those NREs ...

### ISSUE THREAD

**Issue by 7ranceaddic7** [net-lisias-ksp/TweakScale#2] opened 2018-10-21 02:49 UTC
We were dealing with NREs on pellior0's repo (https://github.com/pellinor0/TweakScale/issues/81#issue-364296922).  Since you've done gone jumped in the deep-end, I'm closing out that issue and re-igniting the fire over here.

Linux 18.04
KSP 1.4.5
ModList: [KSP_test_TC.ckan.txt](https://github.com/net-lisias-ksp/TweakScale/files/2498672/KSP_test_TC.ckan.txt)

Something you may find of use...

If you add in 'Decouple With Control' to the above install, generates 436 NREs, starting with the original ...

[ERR 17:07:00.380] [TweakScale] Exception on writeDryCost: System.NullReferenceException: Object reference not set to an instance of an object
  at PartModuleList.Contains (Int32 classID) [0x00000] in <filename unknown>:0 
  at PartModuleList.Contains (System.String className) [0x00000] in <filename unknown>:0 
  at TweakScale.PrefabDryCostWriter.WriteDryCost () [0x00000] in <filename unknown>:0 
[LOG 17:07:00.380] [TweakScale] part=kerbalEVA ()

and ending with ...

[ERR 17:07:00.557] [TweakScale] Exception on writeDryCost: System.NullReferenceException: Object reference not set to an instance of an object
  at PartModuleList.Contains (Int32 classID) [0x00000] in <filename unknown>:0 
  at PartModuleList.Contains (System.String className) [0x00000] in <filename unknown>:0 
  at TweakScale.PrefabDryCostWriter.WriteDryCost () [0x00000] in <filename unknown>:0 
[LOG 17:07:00.557] [TweakScale] part=roverWheel3 (RoveMax Model XL3)

**Comment by Lisias** [comment] 2018-10-22 09:15
Yes, this is exactly the reason we are still in PRE-RELEASE. I have nailed down a root cause, the `Decouple With Control` mod is just another "screaming victim". 

Good to know you found another add-on, so I now I have another confirmation - what reassure me I'm on the correct path.

I'm considering my options at the moment, the less desirable but safest at the moment would be disable support for a whole category of parts until I figure out a really safe solution that would fix this one without blowing up other mods, that what will happen if I tackle this problem punctually disregarding the stability of the rest of the "Universe".

**Comment by 7ranceaddic7** [comment] 2018-10-22 15:47
Good. I've an install set aside for your use.

**Comment by 7ranceaddic7** [comment] 2018-10-24 00:20
I found the culprit.

DeadlyReentry 7.7.0

**Comment by 7ranceaddic7** [comment] 2018-10-31 03:18
So, I I've found another interaction involving RPM, CCTV, HiulcamVDS.

**Comment by 7ranceaddic7** [comment] 2018-10-31 04:51
I am so smart, s m r t.

I've located the kerbalEVA culprit ... HullcamVDS; specifically, FirstPersonEVA.cs.

```
//Add EVA camera to all Kerbals on EVA
[KSPAddon(KSPAddon.Startup.MainMenu, true)]
public class initKerbalEVA : UnityEngine.MonoBehaviour {
	public void Awake() {
           
		ConfigNode EVA = new ConfigNode("MODULE");
		EVA.AddValue("name", "EVACamera");
		EVA.AddValue("cameraName", "EVACam");

		try {
						
			PartLoader.getPartInfoByName("kerbalEVA").partPrefab.AddModule(EVA);
		}
		catch{}
		try { PartLoader.getPartInfoByName("kerbalEVAfemale").partPrefab.AddModule(EVA); 
		}
		catch {}
	}
}
```

**Comment by Lisias** [comment] 2018-11-01 23:44
The HullcamVDS issue is confirmed **TO DO NOT HAPPENS** on KSP 1.4.1 . I just tested it.

It's a Unroly Interaction between HullcamVDS and KSP > 1.4.1.

I made the very same test, with the very same plugins (I literally copied from one GameData to another) using KSP 1.4.3 (without Making History). And… Yes, we have a confirmation, it happens there too.

Both DLLs were compiled by me, and linked agains KSP 1.4.1 libs. I will make a new test, using the DLLs recompiled against the 1.4.3 to see what happens.

**Comment by Lisias** [comment] 2018-11-01 23:54
Test done. No news. Same behaviour.

```
[ERR 20:52:15.960] [TweakScale] Exception on kerbalEVAfemale.prefab.Modules.Contains: System.NullReferenceException: Object reference not
 set to an instance of an object
  at PartModuleList.Contains (Int32 classID) [0x00000] in <filename unknown>:0
  at PartModuleList.Contains (System.String className) [0x00000] in <filename unknown>:0
  at TweakScale.PrefabDryCostWriter+<WriteDryCost>d__4.MoveNext () [0x00000] in <filename unknown>:0
```

This happens on KSP 1.4.3, but not on KSP 1.4.1. Compiling the DLLs against newer KSP libraries doesn't changed the behaviour.

**Comment by 7ranceaddic7** [comment] 2018-11-02 00:10
So, they did something inside the KSPData?

**Comment by Lisias** [comment] 2018-11-02 15:51
HA! Nailed it! :) The answer was there, all the time!

This is the new stackdump after my interventions on HullcamVDS:

```
[EXC 12:29:07.256] NullReferenceException: Object reference not set to an instance of an object
        PartModule.Load (.ConfigNode node)
        Part.AddModule (.ConfigNode node, Boolean forceAwake)
        HullcamVDS.initKerbalEVA+<InstrumentKerbals>d__4.MoveNext ()
        UnityEngine.Debug:LogException(Exception)
        HullcamVDS.<InstrumentKerbals>d__4:MoveNext()
        UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
```

This is what's happening, in verbose mode (from bottom to up)

1. UnityEngine executes my call to start a Coroutine.
2. A loop was entered somewhere up in the foodchain (see the MoveNext).
3. Unity' Debug.LogException is invoked due an Exception. ok, but here? It's the next instruction the culprit, but whatever.
4. HullcamVDS.InstrumentKerbals (inside the coroutine) entered a loop (since the MoveNext, called implicitly by foreach) - it's the Loop where I pick up a part name one by one (kerbalEVA, kerbalEVAfemale, etc)
5. I call the p.partPrefab.AddModule(EVA); implicitly does:
   1.  a Call to Part.AddModule (ok, not so implicit)
   2. a Call to PartModule.Load

On the step 5.2, the Exception aborts anything that AddModule should do in order to keep the GameDatabase's integrity, and that's the reason TweakScale borks later. While searching for the parts I want to instrument, I ask for the Modules from that part, and the (borked) process above leaves the kerbalEVAs with a null on the modules list!

Now I have to figure out by what Kraken's sake PartModule.Load is failing. 

But in a way or another, it's not TweakScale fault! So I'm closing this.

**Comment by Lisias** [comment] 2018-11-02 15:53
This must be handler by HullCamVDS and any other Module that borks while adding a module to a part.

**Comment by Lisias** [comment] 2018-11-24 10:00
This is still not TweakScale problem - the fact is that every add-on is doing their things as it was alone on the system.

Some add-ons took to long to finish their initialization, and since everything and the kitchen's sink are using the MainMenu as a event to start initializations, the sad true is that some add-ons are stomping on TweakScake's feet on that.

Trying to postpone TweakScale initialization solved only the trivial situations - in more complex environments, Race Conditions happens again.

This is not solvable by only one add-on - a Mutual Agreement with every modder on using a solution to solve the concurrency problems (mutexes, semaphores, *et all*) is needed, but it's also unfeasible.

For now, I'm moving TweakScale initialization to the Space Center scene in the hope that nobody else does it too (situation in which TweakScale's feet will be stomped again).

I'm reopening the issue to control the overcome.

**Comment by Lisias** [comment] 2018-11-25 02:32
And now the problem "vanishes" from the logs, besides some side effects being still observable. :)

**Comment by Lisias** [comment] 2018-11-25 17:02
It what I was considering, but since this didn't solved the problem and, worse, **masled** the problem (as I known it's still happening, but the log are being supresses - what's horrible, as it would prevent me to detect the problem on the user's machines.

I only was able to see that the intrinsic problem is still there because the test vessel I'm using gone *kaput* as expected when the problem is present. But the logs were clear!!! o.O

**Comment by Lisias** [comment] 2018-11-30 23:44
This appears to be happening too with KJR on another add-on, Blue-Design-Bureau.

https://github.com/CobaltWolf/Bluedog-Design-Bureau/issues/492

This add-on also uses B9 Parts Switch, what appears to be a trigger on this issue also.

The behaviour described on that issue is almost identical to a issue I had with this vessel when it had B9 Cryogenics tanks. Switching to something else solved the issue.

https://forum.kerbalspaceprogram.com/index.php?/topic/27292-what-did-you-do-in-ksp-today/&do=findComment&comment=3470902

**Comment by Gordon-Dry** [comment] 2018-12-01 00:14
Could the extra node added by Modular Launch Pads to several engines also trigger this?

**Comment by Lisias** [comment] 2018-12-02 08:30
Unlikely. Nodes are just attachment points "hardwired" - as technically you can attach things wherever you want. The attachment points are a kind of guideline.

Of course, only "The Source" knows the Real True - but we can assume what I said with about 95% of confidence. You can add and remove attachment nodes unchecked at runtime, by the way. Would be this an issue, neither TweakScale neither KJR would had ever worked at all.

My best current guess :P is that by some reason (and this time, is not related to concurrency), when TweakScale tries to change a B9 Part Switch Part, something bad happens and the part became 'zeroed' on every attribute (this was confirmed using [Object Inspector](https://forum.kerbalspaceprogram.com/index.php?/topic/151558-151-kerbal-object-inspector-continued-view-all-game-objects-in-ksp/)). This plays havoc with the physics - a vessel of mine collapsed exactly like the one on the https://github.com/CobaltWolf/Bluedog-Design-Bureau/issues/492 , while another blew up on launch: that part became "anchored" on the 3D space and when I applied thrust, things exploded by stress as that part refused to move.

**Comment by Lisias** [comment] 2018-12-04 23:53
This can be related (or not) to issue #11 , [see this comment](url
https://github.com/net-lisias-ksp/TweakScale/issues/11#issuecomment-444304218).

**Comment by Lisias** [comment] 2018-12-29 08:50
I'm finally closing this one reason for the problem was proven to be improper support for the KerbalEVAs on other mods.

Another reason was Race Conditions, that wasn't fixed but was at least mitigated for now by delaying the PreFab phase.

The other reason is related to #11 .

**Closed by Lisias** 2018-12-29 08:50 UTC
Labels: Not My Fault, bug, good first issue
