### ISSUE TITLE
KSPRoot>Gamedata > Tweakscales > Plugins has no scale.dll

### ISSUE THREAD

**Issue by maverickyes** [net-lisias-ksp/TweakScale#241] opened 2022-04-10 23:02 UTC
i was getting all happy to be able to tweak the scale of what i want, finally, after a long time, but it seems that it isn't that easy as this big package is missing the scale.dll plugin

**Comment by Lisias** [comment] 2022-04-11 06:09
Uh… Are you sure?

What link did you used to download TweakScale?

From this https://github.com/net-lisias-ksp/TweakScale/releases/tag/RELEASE%2F2.4.6.10

I just downloaded both distribution files, and (double) confirmed all the files are on the zip - and since there ones are the reference packages I use to feed SpaceDock and CurseForge, a master bork as this one would be surely caught by the first downloaders

Please check the source from where you downloaded the package.

**Comment by maverickyes** [comment] 2022-04-11 11:10
[
![image](https://user-images.githubusercontent.com/103391248/162727886-f6a25347-8619-43c3-9efa-8f598db55bc3.png)
](url)

this is the directory from the zip file that i download once again, scale.dll is missing and i downloaded this one "master" on github

**Comment by maverickyes** [comment] 2022-04-11 11:12
![image](https://user-images.githubusercontent.com/103391248/162728184-37361b48-46f8-431f-ae46-23342b2ae98b.png)

it does seem to be missing here too

**Comment by maverickyes** [comment] 2022-04-11 11:46
i already downloaded from the link, i was trying to download this one so i could tweak hypermod 2.5 scales but it still seems to bug out and with no scale.dll from this github, it doesn't work

**Comment by Lisias** [comment] 2022-04-11 15:20
> [ ![image](https://user-images.githubusercontent.com/103391248/162727886-f6a25347-8619-43c3-9efa-8f598db55bc3.png) ](url)
> 
> this is the directory from the zip file that i download once again, scale.dll is missing and i downloaded this one "master" on github

Ah, found the problem! You are downloading the `Source code.zip` link! :)

Download the `[TweakScale-2.4.6.10.zip](https://github.com/net-lisias-ksp/TweakScale/releases/download/RELEASE%2F2.4.6.10/TweakScale-2.4.6.10.zip)` one. This is where all the needed binaries are!!

**Comment by Lisias** [comment] 2022-04-15 08:59
@maverickyes can I close this?

**Comment by Lisias** [comment] 2022-05-06 20:48
Closing *in absentia* (learnt this yesterday! :D )

**Closed by Lisias** 2022-05-06 20:48 UTC
Labels: unrelated, support
