### ISSUE TITLE
Possible TweakScale Issue - Doubling Electric Charge On Part

### ISSUE THREAD

**Issue by utoxin** [net-lisias-ksp/TweakScale#66] opened 2019-07-31 00:42 UTC
I may have a station that is suffering from a TweakScale related issue, based on the warnings you've posted with the recent versions, but I'm not positive.

KSP Version: 1.7.3.2594
TweakScale Version: 2.4.3.1
Mod of affected part: Kerbalism 3.0.2

Symptoms:
Some unknown event (possibly related to saving/loading) is causing the electric charge on one of the parts in my space station to double. It's currently at 3.5 million and change.

I've dug through the save game and looked at the craft data in the save, and there's definitely some odd module duplicates, but I'm not sure if they're supposed to be there or not.

Save File: [persistent.zip](https://github.com/net-lisias-ksp/TweakScale/files/3449315/persistent.zip)

The craft in question is Space Station One.

Let me know if you need something else.

**Comment by Lisias** [comment] 2019-07-31 12:33
Can you please publish also the full KSP.log and also the ModuleManager ConfigCache? I need them in order to inspect what was done to the parts, as the order of the patching sometimes leads to the problems. I can't even start your savegame without knowing the Add'ons you have, and this information is on the KSP.log.

**Comment by utoxin** [comment] 2019-07-31 14:30
Yep, sorry about the delay is getting this. :) I crashed pretty shortly after I posted this last night.

**Comment by utoxin** [comment] 2019-07-31 14:48
[KSP.log](https://github.com/net-lisias-ksp/TweakScale/files/3452432/KSP.log)

I can't mind a ConfigCache in where I understand it should be. Screenshot of the files in my GameData:

![image](https://user-images.githubusercontent.com/127430/62222086-f8e4d980-b36f-11e9-8729-0221ad9f4a5c.png)

**Comment by utoxin** [comment] 2019-07-31 15:11
If it'll help you... CKAN export of my installed mods.
[Utoxin.zip](https://github.com/net-lisias-ksp/TweakScale/files/3452570/Utoxin.zip)

**Comment by Lisias** [comment] 2019-08-02 15:11
I'm sorry the delay, I got busy at work. If we manage to get a ConfigCache for the WeekEnd, I will reserve time for this issue for sure!


> I can't find a ConfigCache in where I understand it should be. Screenshot of the files in my GameData:

Ugh. That means that there're patches with syntax errors or something. This prevents MM to save the ConfigCache. So let's fix'em first, then you can generate a ConfigCache. This will help me a lot to diagnose the problem! Really.

On the bright side, I found only one:

```
[ERR 2019-07-31 08:39:53.166] Error - Cannot parse variable search when inserting new key ec_rate = #$../MODULE[ModuleSCANresourceScanner]/RESOURCE[ElectricCharge]/rate$

<cut>

[WRN 2019-07-31 08:40:03.660] Errors in patch prevents the creation of the cache
[LOG 2019-07-31 08:40:03.762] ModuleManager: 15692 patches applied, found <color=orange>1 error</color>
1 error related to GameData/Kerbalism/Support/SCANsat.cfg

```

Reach the Kerbalism Maintainer with this report and ask them what to do. I don't have a clue about it, otherwise I would propose a quick&dirty workaround that would allow us to keep going.

**Comment by utoxin** [comment] 2019-08-12 14:09
Alright, not having much luck yet, but with the help of the Kerbalism devs, I was able to isolate the part causing the ModuleManager error.

The mod in question is the OctoSat mod, and I'm not actually using any parts from it yet, so you can safely drop it from the collection and load my save.

**Comment by utoxin** [comment] 2019-08-12 14:10
Here's my ConfigCache after updating all mods in my collection, and removing OctoSat Continued.
[ModuleManager-ConfigCache.zip](https://github.com/net-lisias-ksp/TweakScale/files/3492841/ModuleManager-ConfigCache.zip)

**Comment by Lisias** [comment] 2019-08-14 06:12
Well, I think I'll finally have time to help you. I foresee that whatever is affecting your savegame, will need a Hot Fix (see the news on the TweakScake thread on the forum), so I decided to implement the feature before giving your issue another try.

It will not be today, as I have to work. But my next time slot is yours. :)

Let's crack this nut.

**Comment by utoxin** [comment] 2019-08-14 15:25
Excellent. I'm ready to help out however I can. :) Thanks for all the hard work.

**Comment by Lisias** [comment] 2019-08-15 10:01
Found it!!!

Checking the ConfigCache about it.

```
                        PART
                        {
                                name = utility-pod-25
                                cid = 4289445612
                                <CUT>
                                RESOURCE
                                {
                                        name = ElectricCharge
                                        amount = 3542132.7611800102
                                        maxAmount = 3542806.6800000002
                                        flowState = True
                                        isTweakable = True
                                        hideFlow = False
                                        isVisible = True
                                        flowMode = Both
                                }
```

**Comment by Lisias** [comment] 2019-08-15 10:12
Looking on the ConfigCache, there's not obvious there. Yes, there're some duplicated modules but in this case, it's intentional The Module ProcessControler is instantiated for each resource it monitors, so it's normal behaviour.

Looking on the KSP.log, i see that this part is from NearFutureSpacecraftParts from Nertea. And I also found Kerbalism applying a patch to it. I remember (subject to be confirmed, I need to check to be sure) Nertea (or perhaps some other Author from a popular Add'On) talking about Kerbalism causing unexpected interferences on this parts, and perhaps this is one of them.

Can you confirm to me if the problem happens on Saving/Loading? This can reduce the scope of the search on the code, as I will check the Loading/Saving events of the Add'On's source code and see if I get something from there.

There's a way to fix the part by brute force, but I'm unaware of the side effects. I will pursue this line of action too.

I'm still on it, may need a couple of days, but I'll be back!

**Comment by Lisias** [comment] 2019-08-15 21:08
There are all the patches applied to the `utility-pod-25`:

```
[LOG 2019-07-31 08:38:27.289] Applying update KerbalismConfig/System/ScienceRework/HardDriveConfigs/@PART[*]:HAS[@MODULE[ModuleScienceContainer]]:NEEDS[FeatureScience] to NearFutureSpacecraft/Parts/Command/command-pods/utility-pod-25.cfg/PART
[LOG 2019-07-31 08:38:28.862] Applying update KerbalismConfig/System/ScienceRework/NewScience/@PART[*]:HAS[@MODULE:HAS[#experimentID[crewReport]]]:NEEDS[FeatureScience] to NearFutureSpacecraft/Parts/Command/command-pods/utility-pod-25.cfg/PART
[LOG 2019-07-31 08:38:32.290] Applying update NearFutureSpacecraft/Patches/NFSpacecraftConnectedLivingSpaces/@PART[utility-pod-25]:NEEDS[ConnectedLivingSpace] to NearFutureSpacecraft/Parts/Command/command-pods/utility-pod-25.cfg/PART
[LOG 2019-07-31 08:38:32.989] Applying update REPOSoftTech/AmpYear/MMConfigAmpYear/@PART[*]:HAS[!MODULE[KerbalEVA],!MODULE[FlagSite]]:NEEDS[AmpYear] to NearFutureSpacecraft/Parts/Command/command-pods/utility-pod-25.cfg/PART
[LOG 2019-07-31 08:39:00.198] Applying update KerbalismConfig/Profiles/Default/@PART[*]:HAS[#CrewCapacity[>0],!MODULE[KerbalSeat]]:NEEDS[ProfileDefault]:FOR[Kerbalism] to NearFutureSpacecraft/Parts/Command/command-pods/utility-pod-25.cfg/PART
[LOG 2019-07-31 08:39:00.725] Applying update KerbalismConfig/Profiles/Default/@PART[*]:HAS[@MODULE[Configure]]:NEEDS[ProfileDefault]:FOR[Kerbalism] to NearFutureSpacecraft/Parts/Command/command-pods/utility-pod-25.cfg/PART
[LOG 2019-07-31 08:39:01.149] Applying update KerbalismConfig/System/Habitat/@PART[*]:HAS[!MODULE[Habitat],#CrewCapacity[>0],!MODULE[KerbalSeat]]:NEEDS[FeatureHabitat]:FOR[Kerbalism] to NearFutureSpacecraft/Parts/Command/command-pods/utility-pod-25.cfg/PART
[LOG 2019-07-31 08:39:01.659] Applying update KerbalismConfig/System/Planner/@PART[*]:HAS[@MODULE[ModuleGenerator],!MODULE[LaunchClamp]]:FOR[Kerbalism] to NearFutureSpacecraft/Parts/Command/command-pods/utility-pod-25.cfg/PART
[LOG 2019-07-31 08:39:02.339] Applying update KerbalismConfig/System/Reliability/@PART[*]:HAS[#CrewCapacity[>0],!MODULE[KerbalSeat]]:NEEDS[ProfileDefault,FeatureReliability]:FOR[Kerbalism] to NearFutureSpacecraft/Parts/Command/command-pods/utility-pod-25.cfg/PART
[LOG 2019-07-31 08:39:10.433] Applying update KerbalismConfig/System/ScienceRework/NewScience/@PART[*]:HAS[@MODULE[Experiment]]:NEEDS[FeatureScience]:FOR[Kerbalism] to NearFutureSpacecraft/Parts/Command/command-pods/utility-pod-25.cfg/PART
[LOG 2019-07-31 08:39:12.406] Applying update KerbalismConfig/System/ScienceRework/ModSupport/DMagicOrbitalScience/@PART[*]:HAS[@MODULE[Experiment]]:NEEDS[DMagicOrbitalScience,FeatureScience]:FOR[Kerbalism] to NearFutureSpacecraft/Parts/Command/command-pods/utility-pod-25.cfg/PART
[LOG 2019-07-31 08:39:14.731] Applying update KerbalismConfig/System/Reliability/@PART[*]:HAS[@MODULE[Reliability],!MODULE[KerbalEVA]]:AFTER[Kerbalism] to NearFutureSpacecraft/Parts/Command/command-pods/utility-pod-25.cfg/PART
[LOG 2019-07-31 08:39:15.093] Applying update KerbalismConfig/System/Reliability/@PART[*]:HAS[@MODULE[Reliability],!MODULE[KerbalEVA]]:AFTER[Kerbalism] to NearFutureSpacecraft/Parts/Command/command-pods/utility-pod-25.cfg/PART
[LOG 2019-07-31 08:39:15.784] Applying update WarpPlugin/Patches/Kerbalism/@PART[*]:HAS[!MODULE[KerbalismHabitatController],@MODULE[Habitat]]:NEEDS[FeatureRadiation]:AFTER[Kerbalism] to NearFutureSpacecraft/Parts/Command/command-pods/utility-pod-25.cfg/PART
[LOG 2019-07-31 08:39:16.122] Applying update kOS/kOS-module-manager/@PART[*]:FOR[kOS] to NearFutureSpacecraft/Parts/Command/command-pods/utility-pod-25.cfg/PART
[LOG 2019-07-31 08:39:35.153] Applying update WarpPlugin/Patches/SquadGenerator/@PART[*]:HAS[@MODULE[ModuleGenerator],!MODULE[FNGenerator*],!MODULE[ThermalElectricEffectGenerator],!MODULE[*PowerGenerator]]:FOR[WarpPlugin] to NearFutureSpacecraft/Parts/Command/command-pods/utility-pod-25.cfg/PART
[LOG 2019-07-31 08:39:52.580] Applying update Kerbalism/Support/NearFuture/@PART[utility-pod-25]:NEEDS[NearFutureSpacecraft,FeatureHabitat,FeatureRadiation]:AFTER[zzzKerbalism] to NearFutureSpacecraft/Parts/Command/command-pods/utility-pod-25.cfg/PART
[LOG 2019-07-31 08:39:53.370] Applying update KerbalismConfig/System/Habitat/@PART[*]:HAS[#CrewCapacity[>0],@RESOURCE[ElectricCharge]]:NEEDS[ProfileDefault]:AFTER[zzzKerbalism] to NearFutureSpacecraft/Parts/Command/command-pods/utility-pod-25.cfg/PART
[LOG 2019-07-31 08:39:59.446] Applying update InterstellarFuelSwitch/PatchManager/ActiveMMPatches/IntegratedDecoupler/@PART[*]:FINAL to NearFutureSpacecraft/Parts/Command/command-pods/utility-pod-25.cfg/PART
[LOG 2019-07-31 08:40:00.612] Applying update WarpPlugin/Patches/OreTanksFix/@PART[*]:FINAL to NearFutureSpacecraft/Parts/Command/command-pods/utility-pod-25.cfg/PART
```

(for further analysis as I have time to it)

**Comment by utoxin** [comment] 2019-08-21 15:24
Oops. I just noticed this. I wish Github notified better about comments on issues.

**Comment by utoxin** [comment] 2019-08-21 15:25
As far as confirming that it happens on Save/Load... that's my best theory, but it isn't happening on EVERY save/load cycle, so I'm not sure if there's just some specific situation where it does, or if there's something else that's rare.

**Comment by utoxin** [comment] 2019-08-21 17:08
If I just edit those values in the save to what they should be, is there anything else you saw broken? As far as I've seen, this is my only craft having a problem, and I can attempt to monitor it for the issue re-occuring.

**Comment by Lisias** [comment] 2019-08-25 22:15
From my further testings, I wondering that the problem is on the Pack/Unpack events and the Save/Load being the events where you are able to detect the misbehaviour.

I got another dude with an misbehaviour that it's sure happens on Pack/Unpack. That guy "solved" his issue uninstalling IFS, but it's unlikely (very unlikely) that it would be an IFS issue - most of the time, some Add'Ons ends up being the trigger or the Screaming Victim of the real problem.

I'm spending some spare time now on this. I will post again with my findings, including the results of hot patching on the savegame.

**Comment by Lisias** [comment] 2019-08-26 00:09
I stalled.

I tried to run the savegame without restock, and KSP complained about missing some parts called `restock-*` . Allright, so I installed Restock and Restock+. And now KSP is complaining about the absence of some Stock parts. Do you know what the heck is happening?

![Screen Shot 2019-08-25 at 20 47 05](https://user-images.githubusercontent.com/64334/63657897-ab943600-c77c-11e9-97cf-8beaf5b69471.png)

**Comment by utoxin** [comment] 2019-08-26 00:40
Hrm. It's possible Restock is replacing those parts in such a way that they don't register correctly without the mod? I'm not sure... I can try on my end, but it'll probably do the same thing.

**Comment by Lisias** [comment] 2019-08-31 03:56
Well… I can't build a test bed for this savegame, so I cannot try things to see what happens. Neither to try to diagnose the problem.

My best guess is something happening on the Pack/Unpack events, that fits on the behaviour you described too - as Saving/Loading also ends up calling Pack/Unpack on the craft, and I know [another guy](https://forum.kerbalspaceprogram.com/index.php?/topic/186031-ship-exploding-when-rendezvous-with-another-vessel/&do=findComment&comment=3645504) with a problem exactly on these two events.

They workarounded his problem by uninstalling InterstellarFuelSwitch. Do you mind giving it a try?

**Comment by Lisias** [comment] 2019-09-02 03:38
In time, I found this tool that can help editing the persistence.sfs

https://forum.kerbalspaceprogram.com/index.php?/topic/133971-win-kml-persistence-file-editor/

**Comment by Lisias** [comment] 2019-10-06 13:25
I Could not reproduce an installment to really pursue the matter, so this issue is definitively stalled.

Workarounds were proposed, so I'm closing this.

**Closed by Lisias** 2019-10-06 13:25 UTC
Labels: question
