### ISSUE TITLE
[Bug Report]Fairing Part cann't tweakscale right

### ISSUE THREAD

**Issue by zkx741481546** [net-lisias-ksp/TweakScale#83] opened 2019-11-03 06:24 UTC
KSP 1.7.3
TweakScale
"VERSION":{
		"MAJOR":2,
		"MINOR":4,
		"PATCH":3,
		"BUILD":10
		},

Bug:
If use TweakScale on KWRocketRebalanced  Fairing, the FairingShell won't be tweakScale, which will make them separate with each other.

Also, some parts name has been changed in KWRocketRebalanced, but the config file in TweakScale is not updated, so parts like KW Fairing cann't use TweakScale now,please Fix It.

**Comment by Lisias** [comment] 2019-11-03 15:47
This is something to be handled by KWRocketRebalanced guys, not for me.

I don't plan to integrate into TweakScale support for every single Add'On in existence out there - it's just impossible to do a proper job. This must be implemented and maintained by the Add'Ons themselves, or by third-parties willing to do the job.

Anyway, Fairings are still Work in Progress, see Issue #75 , so this probably need to wait until TweakScale 2.4.4.x series.

**Comment by Lisias** [comment] 2019-11-03 15:50
Being out of TweakScale to support itself every Add'On in existence, TweakScale relies on contributions to do that.

But historically, internalizing these patches into TweakScale default patches leaded to overload and fast bit-rotting of these patches as time goes by.

Due this, I'm closing this as "Works as Intended". I will support and collaborate to anyone willing to create an companion Add'On to be installed by TweakScale and KWRocketRebalanced users.

**Closed by Lisias** 2019-11-03 15:50 UTC
Labels: works as intended
